DROP TABLE IF EXISTS pedido_itens CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS produtos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'cliente',
    ativo SMALLINT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_tipo_check CHECK (tipo IN ('admin', 'cliente'))
);

CREATE TABLE produtos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT NOT NULL,
    preco NUMERIC(10, 2) NOT NULL,
    imagem VARCHAR(255),
    categoria VARCHAR(100),
    destaque SMALLINT NOT NULL DEFAULT 0,
    ativo SMALLINT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pedidos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    cliente_nome VARCHAR(150) NOT NULL,
    cliente_telefone VARCHAR(40) NOT NULL,
    cliente_endereco VARCHAR(255) NOT NULL,
    tipo_entrega VARCHAR(20) NOT NULL DEFAULT 'retirada',
    observacoes TEXT,
    total NUMERIC(10, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Novo',
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pedidos_tipo_entrega_check CHECK (tipo_entrega IN ('retirada', 'motoboy')),
    CONSTRAINT fk_pedidos_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE pedido_itens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL,
    produto_id INTEGER,
    nome_produto VARCHAR(150) NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_itens_pedidos FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE
);

CREATE INDEX idx_pedidos_usuario_id ON pedidos(usuario_id);
CREATE INDEX idx_pedido_itens_pedido_id ON pedido_itens(pedido_id);

INSERT INTO usuarios (nome, email, senha, tipo, ativo) VALUES
('Administrador', 'admin@doranina.com', '$2y$12$Yk5sVW7nRnjVdA1xKywThOlisig2Q0x.WB/VJFkj2TRZZ1fPYteBW', 'admin', 1);

INSERT INTO produtos (nome, descricao, preco, imagem, categoria, destaque, ativo) VALUES
('Cenourinha', 'Bolo de cenoura com cobertura de brigadeiro gourmet de chocolate meio amargo.', 30.00, 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=900&q=80', 'Com cobertura', 1, 1),
('Chocolate', 'Bolo de chocolate com cobertura de brigadeiro gourmet de chocolate meio amargo.', 40.00, 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80', 'Com cobertura', 1, 1),
('Formigueiro', 'Bolo formigueiro com cobertura de brigadeiro de chocolate meio amargo.', 35.00, 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=900&q=80', 'Com cobertura', 0, 1),
('Laranjinha', 'Bolo de laranja suave com cobertura de brigadeiro de laranja.', 30.00, 'https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=900&q=80', 'Com cobertura', 0, 1),
('Limao Siciliano com Mirtilo', 'Bolo especial com cobertura de ganache de chocolate branco.', 40.00, 'https://images.unsplash.com/photo-1562440499-64c9a111f713?auto=format&fit=crop&w=900&q=80', 'Especiais', 1, 1),
('Coco com Tapioca', 'Com calda de leite de coco, doce de leite e finalizacao com coco ralado.', 35.00, 'https://images.unsplash.com/photo-1535141192574-5d4897c12636?auto=format&fit=crop&w=900&q=80', 'Especiais', 0, 1);
